Multifacet / Range chart additional props
newrelic/nr1-victory-visualizations pull request #33
Opened 2021-05-21 09:08 UTC by caylahamann

Adds four additional props to the multifacet bar chart: 
* y axis maximum value 
* y axis minimum value 
* y axis label 
* visibility of other group 

Adds one addition prop to the range chart: 
* visibility of other group

2021-05-21 19:41 UTC, JuliaNocera commented on visualizations/multifacet-bar-chart/nr1.json
> +      "items": [
curious to know why this is nested under a namespace rather than a top level boolean field?

2021-05-21 19:42 UTC, JuliaNocera commented on visualizations/range-chart/nr1.json
> +      "items": [
same question as the other configuration for "Other visible"

2021-05-21 19:44 UTC, JuliaNocera commented on visualizations/multifacet-bar-chart/nr1.json
> +      "items": [
Ahh ok, I see. This brings it in line with the current vizco config for other groups. Nevermind!

2021-05-21 21:54 UTC, tyreer commented on visualizations/stacked-bar-chart/index.js
> +    yAxisConfig: PropTypes.shape({
Should we add a comment to define these prop types? Looks like we've done so over in `CircularProgressBar`

```
  static propTypes = {
    /**
     * An array of objects consisting of a nrql `query` and `accountId`.
     * This should be a standard prop for any NRQL based visualizations.
     */
    nrqlQueries: PropTypes.arrayOf(
      PropTypes.shape({
        accountId: PropTypes.number,
        query: PropTypes.string,
      })
    ),

    /**
     * Configuration that determines what values to display as critical or
     * successful.
     */
    thresholds: PropTypes.shape({
      criticalThreshold: PropTypes.number,
      highValuesAreSuccess: PropTypes.bool,
    }),
  };
```

2021-05-21 21:55 UTC, tyreer commented on visualizations/range-chart/index.js
> +    other: PropTypes.shape({
Should we add a comment to define this prop types? 

Looks like we've done so over in `CircularProgressBar`

2021-05-21 22:55 UTC, jerelmiller requested changes
I'm not seeing a field for the NRQL query or account ID. Was that intentionally removed? I can re-review once that is confirmed. Without the query, I'm not really sure how best to configure the chart:

<img width="1906" alt="Screen Shot 2021-05-21 at 3 55 32 PM" src="https://user-images.githubusercontent.com/565661/119205393-fe337c80-ba4c-11eb-978a-33b362ff3724.png">

2021-05-21 22:55 UTC, jerelmiller commented on visualizations/stacked-bar-chart/nr1.json
> -      "title": "NRQL Queries",
It looks like the NRQL query and account ID disappeared with this change. Was that intentional?

2021-05-21 22:57 UTC, caylahamann commented on visualizations/stacked-bar-chart/nr1.json
> -      "title": "NRQL Queries",
nooooo definitely not, must have happened during a merge conflict. Let me fix that real quick.

2021-05-21 23:20 UTC, jerelmiller requested changes
After trying this locally, a couple things jump out at me that are a bit strange.

1) The y-axis step values are a bit strange. Perhaps this is tied to the `numeral` helper we are using, but check out this screenshot. You'll notice each step is duplicated twice. I'm thinking that is likely because we are showing 1 decimal place, but Victory is expecting to see 2 or more. We should look at that.

<img width="1920" alt="Screen Shot 2021-05-21 at 4 14 22 PM" src="https://user-images.githubusercontent.com/565661/119206352-c4b04080-ba4f-11eb-8d7a-8bbe6b048ca5.png">

2) Configuring a `max` value on its own works great, however configuring a `min` value is where things get wonky. Here is the `max` on its own:

<img width="1920" alt="Screen Shot 2021-05-21 at 4 14 22 PM" src="https://user-images.githubusercontent.com/565661/119206573-5ddf5700-ba50-11eb-964b-fdb596d31f32.png">

Using the suggested NRQL query: `FROM Transaction SELECT average(duration) FACET environment, appName`, the data just disappears as soon as I try and enter any kind of `min` value:

<img width="1920" alt="Screen Shot 2021-05-21 at 4 14 08 PM" src="https://user-images.githubusercontent.com/565661/119206511-35eff380-ba50-11eb-91b6-b309d9fcda87.png">

I thought maybe this was due to the fact that I didn't specify a `max`, so I tried that as well, and got the same result:

<img width="1920" alt="Screen Shot 2021-05-21 at 4 14 16 PM" src="https://user-images.githubusercontent.com/565661/119206540-443e0f80-ba50-11eb-8826-23d0b17a69f2.png">

I do see the axis changing, so that is working great.

Could we take a look and see whats going on here?

2021-05-21 23:20 UTC, jerelmiller commented on visualizations/stacked-bar-chart/nr1.json
> +      "name": "yAxisConfig",
[nit] What about simplifying this name to `yAxis` (`yAxis.label`, `yAxis.min`, etc.). Thoughts?

2021-05-21 23:20 UTC, jerelmiller commented on visualizations/stacked-bar-chart/nr1.json
> +          "title": "Max value",
[nit] Would it make sense to simplify these to just `Min` and `Max`? 

Could we also swap the `min` and `max` configs in the array so that `min` shows up on top of `max`?

2021-05-24 16:25 UTC, caylahamann commented
Closing this one til there is a fix for the axis issues in victory

2021-05-24 16:25 UTC, closed without merging