Handles one facet case and provides x axis label in that case
newrelic/nr1-victory-visualizations pull request #54
Opened 2021-05-26 19:33 UTC by caylahamann

2021-05-26 22:03 UTC, tyreer requested changes
Looking great! A couple minor comments in there

2021-05-26 22:03 UTC, tyreer commented on visualizations/stacked-bar-chart/index.js
> +              const { uniqueFacets } = getUniqueAggregatesAndFacets(data);
Do you think we could move this logic out into a method on the class?

Then the call site could be:

```
const {xAxisLabel, xAxisTickFormat} = getXAxisLabelProps(data, xDomainWidth, barCount)
```

Feels like we've got a fair bit going on in `render` already so if there's a chance to wrap this up in a function and isolate it could help focus the `render` code

2021-05-26 23:38 UTC, caylahamann commented on visualizations/stacked-bar-chart/index.js
> +              const { uniqueFacets } = getUniqueAggregatesAndFacets(data);
yeah I was thinking that too, there's too much going on in render

2021-05-27 16:40 UTC, tyreer approved these changes
Thanks for the refactor efforts! Looks real nice and super glad we got the bottom of that error with `e.split` ! 🎉

2021-05-27 16:55 UTC, merged